#!/bin/bash

run_brew() {
    if has "brew"; then
        echo  "Already installed Homebrew!"
    else
        echo "Installing Homebrew..."
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    if has "brew"; then
        echo "Updateing Homebrew..."
        brew update && brew upgrade
        [[ $? ]] && echo "Update Homebrew complete!"

        brew tap 'caskroom/cask'
        brew tap 'sanemat/font'
        brew tap 'homebrew/php'
        brew tap 'greymd/tools'

        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'ffmpeg --with-fdk-aac --with-sdl2 --with-fontconfig --with-freetype --with-frei0r --with-libass --with-libbluray --with-libcaca --with-libsoxr --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-speex --with-theora --with-tools --with-x265 --with-webp'
            'cmake'
            'fontforge'
            'gcc'
            'ghq'
            'gibo'
            'git'
            'mysql'
            'neovim'
            'openssl'
            'peco'
            'postgresql'
            'sqlite'
            'tig'
            'tmux'
            'tree'
            'vim'
            'wget'
            'yarn'
            'zlib'
            'zsh'
        )

        local installed=`brew list`

        for index in ${!desired_formulae[*]}
        do
            local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
            if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            else
                echo "Installed ${formula}"
                [[ "${formula}" = "ricty" ]] && local installed_ricty=true
            fi
        done

        if [[ "$missing_formulae" ]]; then
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            echo "Installing missing Homebrew formulae..."
            brew install $list_formulae

            [[ $? ]] && echo "Installed missing formulae"
        fi

        if [ -z "$=={installed_ricty}"  ]; then
            echo "Reload fonts. This could take a while..."
            local cellar=`brew --config | grep 'HOMEBREW_CELLAR' | cut -d' ' -f 2`
            find ${cellar}/ricty/*/share/fonts/Ricty*.ttf | xargs -I % cp % ~/Library/Fonts
            fc-cache -vf
        fi

    local -a missing_formulae=()
    local -a desired_formulae=(
      'alfred'
      'bettertouchtool'
      'chatwork'
      'dash'
      'dropbox'
      'firefox'
      'franz'
      'google-chrome'
      'iterm2'
      'karabiner-elements'
      'sequel-pro'
      'slack'
      'skitch'
      'skype'
      'trailer'
      'vagrant'
      'xquartz'
    )

    # cask
    local installed=`brew cask list`

    for index in ${!desired_formulae[*]}
    do
        local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
        if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        else
        echo "Installed ${formula}"
        fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew cask install $list_formulae

      [[ $? ]] && echo "Installed missing formulae"
    fi

    echo "Cleanup Homebrew..."
    brew cleanup
    echo "$Cleanup Homebrew complete."
  fi
}
